name: Publish Pages

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:
  push:

jobs:
  sponsor_count_json:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.SPONSOR_GITHUB_TOKEN }}
        with:
          script: |
            const fs = require("fs")
            const query = `query {
              user(login:"${context.repo.owner}") {
                ... on Sponsorable {
                  sponsors(first: 10) {
                    totalCount
                  }
                }
              }
            }`;
            const variables = {}
            const result = await github.graphql(query, variables)
            console.log(result)

            fs.writeFile('./sponsor_count.json', JSON.stringify(result.user), err => {
              if (err) {
                console.error(err);
              } else {
                // file written successfully
              }
            });
      - uses: actions/upload-artifact@v4
        with:
          name: sponsor-count
          path: ./sponsor_count.json
