name: Publish Pages

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:
  push:

jobs:
  sponsor_count_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs")
            const query = `query {
              user(login:"${context.repo.owner}") {
                ... on Sponsorable {
                  sponsors(first: 10) {
                    totalCount
                  }
                }
              }
            }`;
            const variables = {}
            const result = await github.graphql(query, variables)
            console.log(result)

            fs.writeFile('./sponsor_count.json', JSON.stringify(result.user), err => {
              if (err) {
                console.error(err);
              } else {
                // file written successfully
              }
            });
      - uses: actions/upload-artifact@v4
        with:
          name: sponsor-count
          path: ./sponsor_count.json
  merged_platform_zips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const url = "https://raw.githubusercontent.com/mattpannella/pocket-updater-utility/main/image_packs.json"
            const packs = await github.request(url)
            console.log(packs)

      - uses: actions/upload-artifact@v4
        with:
          name: image-packs
          path: ./image_packs
